sudo: false
language: python
matrix:
  include:
    - env: TOXENV=flake8
    - env: TOXENV=isort
    - env: TOXENV=py27-1.11
    - env: TOXENV=py34-1.11
      python: 3.4
    - env: TOXENV=py34-2.0
      python: 3.4
    - env: TOXENV=py35-1.11
      python: 3.5
    - env: TOXENV=py35-2.0
      python: 3.5
    - env: TOXENV=py35-2.1
      python: 3.5
    - env: TOXENV=py35-master
      python: 3.5
    - env: TOXENV=py36-1.11
      python: 3.6
    - env: TOXENV=py36-2.0
      python: 3.6
    - env: TOXENV=py36-2.1
      python: 3.6
    - env: TOXENV=py36-master
      python: 3.6
  fast_finish: true
  allow_failures:
    - env: TOXENV=py35-master
      python: 3.5
    - env: TOXENV=py36-master
      python: 3.6

install:
  - pip install tox coveralls

script:
  - tox

after_success:
  - coveralls
