dist: bionic
sudo: false
language: python
cache: pip
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9
stages:
  - lint
  - test
arch:
  - amd64
  - ppc64le
jobs:
  fast_finish: true
  include:
    - { stage: lint, env: TOXENV=flake8, python: 3.9 }
    - { stage: lint, env: TOXENV=isort, python: 3.9 }
    - { stage: lint, env: TOXENV=flake8, python: 3.9, arch: ppc64le }
    - { stage: lint, env: TOXENV=isort, python: 3.9, arch: ppc64le }

install:
- pip install tox coveralls tox-travis
script:
- tox
after_success:
- if [ -f .coverage ]; then coveralls; fi
before_deploy: "pip install django"
deploy:
  provider: pypi
  user: charettes
  password:
    secure: Ix/iLGKu+usjaNGPIKRzvgdZz8TVxReiMFLorgMpHb9P29tgIBQSDzVmo8gzUi+LF4SQs2AdnuYJY15ap68JX7iLfCuWWYIvIqgMLb3W64jfUDg9KpLJQYCv6cTKQHoDVtVTg0jXJmauEYMMYuqmdrSgZ6rSfpsbajMrveCzVuStb7kd5H4WPX3/j4JfCmr07CyAi85rLAnaIfmCYADWC4nrYll7+0Ugke64C4KstY0l6HYBNTT5ZwJvXSNd0VQd31b5okv8bwjGXzeVrbgIAe+c1p0lS11hsNqfLL/rrnlvgC7P7568TxGwWVmIDJm131r1K7skLscEfCuPbJJ3oqljxLQMQIJ4JbR12HtRwB93dOnJOgCbqySAJAZHUvkm2r3VAO8BJK3xYnJg/2IGrxolDQxwJi2SMEgwqQZx3thTFKXvviiWn5dnLjiNRpSOHUzayCVYga7WAgVksKVMbmtcNrJWwrAHtWLxo9vnM2W+6JNFeXiGIIwGu7qJ/Sz/qCuv/uKibbFqhUJfATXf5HhSJ3yIM/Ef04/SSpBqkYcFcrGLdzzW2Bpv4jscv4EcNyGDxnzeJtvXWVceoW0g7XweUn4b5P+NvOSV4YCjJ04BU4r/upV7+ulkQxnCWot2MD0zhvlodldn+6tGfdBbYJ/KlBHQjwdjFFKaxqRkuyA=
  distributions: sdist bdist_wheel
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION = 3.9"
